In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as snsp
import yfinance as yf

In [3]:
from pathlib import Path

ROOT = Path.cwd() if (Path.cwd() / "data").exists() else Path.cwd().parent
DATA = ROOT / "data"

# si no recuerdas la extensión exacta, tomará xlsx/xls
ruta = next((DATA / "sp500_new").parent.glob("sp500_new.*"))

lista_sp500 = pd.read_excel(ruta)
lista_sp500

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740,1902
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800,1888
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989
...,...,...,...,...,...,...,...,...
499,XYL,Xylem Inc.,Industrials,Industrial Machinery & Supplies & Components,"White Plains, New York",2011-11-01,1524472,2011
500,YUM,Yum! Brands,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,1997
501,ZBRA,Zebra Technologies,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969
502,ZBH,Zimmer Biomet,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,1927
503,ZTS,Zoetis,Health Care,Pharmaceuticals,"Parsippany, New Jersey",2013-06-21,1555280,1952

In [4]:
lista_sp500[lista_sp500["GICS Sector"]=="Health Care"]  # es como hacer un filtro en excel

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800,1888
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
9,A,Agilent Technologies,Health Care,Life Sciences Tools & Services,"Santa Clara, California",2000-06-05,1090872,1999
15,ALGN,Align Technology,Health Care,Health Care Supplies,"Tempe, Arizona",2017-06-19,1097149,1997
32,AMGN,Amgen,Health Care,Biotechnology,"Thousand Oaks, California",1992-01-02,318154,1980
57,BAX,Baxter International,Health Care,Health Care Equipment,"Deerfield, Illinois",1972-09-30,10456,1931
58,BDX,Becton Dickinson,Health Care,Health Care Equipment,"Franklin Lakes, New Jersey",1972-09-30,10795,1897
61,TECH,Bio-Techne,Health Care,Life Sciences Tools & Services,"Minneapolis, Minnesota",2021-08-30,842023,1976
62,BIIB,Biogen,Health Care,Biotechnology,"Cambridge, Massachusetts",2003-11-13,875045,1978
69,BSX,Boston Scientific,Health Care,Health Care Equipment,"Marlborough, Massachusetts",1995-02-24,885725,1979
70,BMY,Bristol Myers Squibb,Health Care,Pharmaceuticals,"New York City, New York",1957-03-04,14272,1989 (1887)
84,CAH,Cardinal Health,Health Care,Health Care Distributors,"Dublin, Ohio",1997-05-27,721371,1971
92,COR,Cencora,Health Care,Health Care Distributors,"Conshohocken, Pennsylvania",2001-08-30,1140859,1985
93,CNC,Centene Corporation,Health Care,Managed Health Care,"St. Louis, Missouri",2016-03-30,1071739,1984
96,CRL,Charles River Laboratories,Health Care,Life Sciences Tools & Services,"Wilmington, Massachusetts",2021-05-14,1100682,1947
103,CI,Cigna,Health Care,Health Care Services,"Bloomfield, Connecticut",1976-06-30,1739940,1982
122,COO,Cooper Companies (The),Health Care,Health Care Supplies,"San Ramon, California",2016-09-23,711404,1958
134,CVS,CVS Health,Health Care,Health Care Services,"Woonsocket, Rhode Island",1957-03-04,64803,1996
135,DHR,Danaher Corporation,Health Care,Life Sciences Tools & Services,"Washington, D.C.",1998-11-18,313616,1969
138,DVA,DaVita,Health Care,Health Care Services,"Denver, Colorado",2008-07-31,927066,1979
145,DXCM,Dexcom,Health Care,Health Care Equipment,"San Diego, California",2020-05-12,1093557,1999
164,EW,Edwards Lifesciences,Health Care,Health Care Equipment,"Irvine, California",2011-04-01,1099800,1958
166,ELV,Elevance Health,Health Care,Managed Health Care,"Indianapolis, Indiana",2002-07-25,1156039,2014 (1946)
209,GEHC,GE HealthCare,Health Care,Health Care Equipment,"Chicago, Illinois",2023-01-04,1932393,1994
217,GILD,Gilead Sciences,Health Care,Biotechnology,"Foster City, California",2004-07-01,882095,1987
225,HCA,HCA Healthcare,Health Care,Health Care Facilities,"Nashville, Tennessee",2015-01-27,860730,1968
227,HSIC,Henry Schein,Health Care,Health Care Distributors,"Melville, New York",2015-03-17,1000228,1932
231,HOLX,Hologic,Health Care,Health Care Equipment,"Marlborough, Massachusetts",2016-03-30,859737,1985
239,HUM,Humana,Health Care,Managed Health Care,"Louisville, Kentucky",2012-12-10,49071,1961
244,IDXX,Idexx Laboratories,Health Care,Health Care Equipment,"Westbrook, Maine",2017-01-05,874716,1983
246,INCY,Incyte,Health Care,Biotechnology,"Wilmington, Delaware",2017-02-28,879169,1991
248,PODD,Insulet Corporation,Health Care,Health Care Equipment,"Acton, Massachusetts",2023-03-15,1145197,2000
256,ISRG,Intuitive Surgical,Health Care,Health Care Equipment,"Sunnyvale, California",2008-06-02,1035267,1995
259,IQV,IQVIA,Health Care,Life Sciences Tools & Services,"Durham, North Carolina",2017-08-29,1478242,1982
265,JNJ,Johnson & Johnson,Health Care,Pharmaceuticals,"New Brunswick, New Jersey",1973-06-30,200406,1886
281,LH,Labcorp,Health Care,Health Care Services,"Burlington, North Carolina",2004-11-01,920148,1978
288,LLY,Lilly (Eli),Health Care,Pharmaceuticals,"Indianapolis, Indiana",1970-12-31,59478,1876
308,MCK,McKesson Corporation,Health Care,Health Care Distributors,"Irving, Texas",1999-01-13,927653,1833
309,MDT,Medtronic,Health Care,Health Care Equipment,"Dublin, Ireland",1986-10-31,1613103,1949
310,MRK,Merck & Co.,Health Care,Pharmaceuticals,"Kenilworth, New Jersey",1957-03-04,310158,1891
313,MTD,Mettler Toledo,Health Care,Life Sciences Tools & Services,"Columbus, Ohio",2016-09-06,1037646,1945
319,MRNA,Moderna,Health Care,Biotechnology,"Cambridge, Massachusetts",2021-07-21,1682852,2010
321,MOH,Molina Healthcare,Health Care,Managed Health Care,"Long Beach, California",2022-03-02,1179929,1980
369,PFE,Pfizer,Health Care,Pharmaceuticals,"New York City, New York",1957-03-04,78003,1849
389,DGX,Quest Diagnostics,Health Care,Health Care Services,"Secaucus, New Jersey",2002-12-12,1022079,1967
395,REGN,Regeneron Pharmaceuticals,Health Care,Biotechnology,"Tarrytown, New York",2013-05-01,872589,1988
398,RMD,ResMed,Health Care,Health Care Equipment,"San Diego, California",2017-07-26,943819,1989
399,RVTY,Revvity,Health Care,Health Care Equipment,"Waltham, Massachusetts",1985-05-31,31791,1937
418,SOLV,Solventum,Health Care,Health Care Technology,"Saint Paul, Minnesota",2024-04-01,1964738,2023
425,STE,Steris,Health Care,Health Care Equipment,"Dublin, Ireland",2019-12-23,1757898,1985
426,SYK,Stryker Corporation,Health Care,Health Care Equipment,"Kalamazoo, Michigan",2000-12-12,310764,1941
444,TMO,Thermo Fisher Scientific,Health Care,Life Sciences Tools & Services,"Waltham, Massachusetts",2004-08-03,97745,2006 (1902)
464,UNH,UnitedHealth Group,Health Care,Managed Health Care,"Minnetonka, Minnesota",1994-07-01,731766,1977
465,UHS,Universal Health Services,Health Care,Health Care Facilities,"King of Prussia, Pennsylvania",2014-09-20,352915,1979
472,VRTX,Vertex Pharmaceuticals,Health Care,Biotechnology,"Boston, Massachusetts",2013-09-23,875320,1989
473,VTRS,Viatris,Health Care,Pharmaceuticals,"Pittsburgh, Pennsylvania",2004-04-23,1792044,1961
486,WAT,Waters Corporation,Health Care,Life Sciences Tools & Services,"Milford, Massachusetts",2002-01-02,1000697,1958
490,WST,West Pharmaceutical Services,Health Care,Health Care Supplies,"Exton, Pennsylvania",2020-05-22,105770,1923
502,ZBH,Zimmer Biomet,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,1927
503,ZTS,Zoetis,Health Care,Pharmaceuticals,"Parsippany, New Jersey",2013-06-21,1555280,1952

In [5]:
list_health_ss=lista_sp500[lista_sp500["GICS Sub-Industry"]=="Health Care Equipment"]
list_health_ss

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800,1888
57,BAX,Baxter International,Health Care,Health Care Equipment,"Deerfield, Illinois",1972-09-30,10456,1931
58,BDX,Becton Dickinson,Health Care,Health Care Equipment,"Franklin Lakes, New Jersey",1972-09-30,10795,1897
69,BSX,Boston Scientific,Health Care,Health Care Equipment,"Marlborough, Massachusetts",1995-02-24,885725,1979
145,DXCM,Dexcom,Health Care,Health Care Equipment,"San Diego, California",2020-05-12,1093557,1999
164,EW,Edwards Lifesciences,Health Care,Health Care Equipment,"Irvine, California",2011-04-01,1099800,1958
209,GEHC,GE HealthCare,Health Care,Health Care Equipment,"Chicago, Illinois",2023-01-04,1932393,1994
231,HOLX,Hologic,Health Care,Health Care Equipment,"Marlborough, Massachusetts",2016-03-30,859737,1985
244,IDXX,Idexx Laboratories,Health Care,Health Care Equipment,"Westbrook, Maine",2017-01-05,874716,1983
248,PODD,Insulet Corporation,Health Care,Health Care Equipment,"Acton, Massachusetts",2023-03-15,1145197,2000
256,ISRG,Intuitive Surgical,Health Care,Health Care Equipment,"Sunnyvale, California",2008-06-02,1035267,1995
309,MDT,Medtronic,Health Care,Health Care Equipment,"Dublin, Ireland",1986-10-31,1613103,1949
398,RMD,ResMed,Health Care,Health Care Equipment,"San Diego, California",2017-07-26,943819,1989
399,RVTY,Revvity,Health Care,Health Care Equipment,"Waltham, Massachusetts",1985-05-31,31791,1937
425,STE,Steris,Health Care,Health Care Equipment,"Dublin, Ireland",2019-12-23,1757898,1985
426,SYK,Stryker Corporation,Health Care,Health Care Equipment,"Kalamazoo, Michigan",2000-12-12,310764,1941
502,ZBH,Zimmer Biomet,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,1927

In [6]:
print(type(list_health_ss))

<class 'pandas.core.frame.DataFrame'>

In [7]:
list_health_ss.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17 entries, 2 to 502
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Symbol                 17 non-null     object
 1   Security               17 non-null     object
 2   GICS Sector            17 non-null     object
 3   GICS Sub-Industry      17 non-null     object
 4   Headquarters Location  17 non-null     object
 5   Date added             17 non-null     datetime64[ns]
 6   CIK                    17 non-null     int64
 7   Founded                17 non-null     object
dtypes: datetime64[ns](1), int64(1), object(6)
memory usage: 1.2+ KB

In [8]:
tickers_health_ss=list_health_ss["Symbol"].tolist()  #tomo la colummna symbol del dataframe y la convierto en  lista y la guardo en tickers_health_ss
tickers_health_ss

['ABT',
 'BAX',
 'BDX',
 'BSX',
 'DXCM',
 'EW',
 'GEHC',
 'HOLX',
 'IDXX',
 'PODD',
 'ISRG',
 'MDT',
 'RMD',
 'RVTY',
 'STE',
 'SYK',
 'ZBH']

In [9]:
print("Primer ticker de la lista",tickers_health_ss[0])
print("Ultimo ticker de la lista",tickers_health_ss[-1])

Primer ticker de la lista ABT
Ultimo ticker de la lista ZBH

In [10]:
# USO DEL COMANDO TICKER 
df1=yf.Ticker(tickers_health_ss[0])
df1.info  #estoy interesado en la primera empresa de la lista y despues del punto ponemos info y vemos toda su informacion ademas de la financiera

{'address1': '100 Abbott Park Road',
 'address2': 'Abbott Park',
 'city': 'North Chicago',
 'state': 'IL',
 'zip': '60064-6400',
 'country': 'United States',
 'phone': '224 667 6100',
 'website': 'https://www.abbott.com',
 'industry': 'Medical Devices',
 'industryKey': 'medical-devices',
 'industryDisp': 'Medical Devices',
 'sector': 'Healthcare',
 'sectorKey': 'healthcare',
 'sectorDisp': 'Healthcare',
 'longBusinessSummary': "Abbott Laboratories, together with its subsidiaries, discovers, develops, manufactures, and sells health care products worldwide. It operates in four segments: Established Pharmaceutical Products, Diagnostic Products, Nutritional Products, and Medical Devices. The company provides generic pharmaceuticals for the treatment of pancreatic exocrine insufficiency, irritable bowel syndrome or biliary spasm, intrahepatic cholestasis or depressive symptoms, gynecological disorder, hormone replacement therapy, dyslipidemia, hypertension, hypothyroidism, hypertriglyceridemia, Ménière's disease and vestibular vertigo, pain, fever, inflammation, and migraine, as well as provides anti-infective clarithromycin, influenza vaccine, and products to regulate physiological rhythm of the colon. It also offers laboratory and transfusion medicine systems in the areas of immunoassay, clinical chemistry, hematology, and transfusion serology testing; molecular diagnostics polymerase chain reaction instrument systems that automate the extraction, purification, and preparation of DNA and RNA from patient samples, and detect and measure infectious agents; point of care systems; cartridges for testing blood gas, chemistry, electrolytes, coagulation, and immunoassay; rapid diagnostics lateral flow testing products; molecular point-of-care testing for HIV, SARS-CoV-2, influenza A and B, RSV, and strep A; cardiometabolic test systems; and drug and alcohol test. In addition, the company provides pediatric and adult nutritional products and infant formula; rhythm management, electrophysiology, heart failure, vascular, and structural heart devices for the treatment of cardiovascular diseases; diabetes care products, such as glucose and blood glucose monitoring systems; and neuromodulation devices for the management of chronic pain and movement disorders. Abbott Laboratories was founded in 1888 and is based in North Chicago, Illinois.",
 'fullTimeEmployees': 114000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Robert B. Ford',
   'age': 50,
   'title': 'Chairman of the Board, President & CEO',
   'yearBorn': 1974,
   'fiscalYear': 2022,
   'totalPay': 4980248,
   'exercisedValue': 9807163,
   'unexercisedValue': 64376952},
  {'maxAge': 1,
   'name': 'Mr. Philip P. Boudreau',
   'age': 51,
   'title': 'CFO & Executive VP of Finance',
   'yearBorn': 1973,
   'fiscalYear': 2022,
   'totalPay': 2183487,
   'exercisedValue': 0,
   'unexercisedValue': 814501},
  {'maxAge': 1,
   'name': 'Mr. Daniel Gesua Sive Salvadori',
   'age': 45,
   'title': 'Executive VP and Group President of Established Pharmaceuticals & Nutritional Products',
   'yearBorn': 1979,
   'fiscalYear': 2022,
   'totalPay': 1891684,
   'exercisedValue': 0,
   'unexercisedValue': 29351640},
  {'maxAge': 1,
   'name': 'Ms. Lisa D. Earnhardt',
   'age': 54,
   'title': 'Executive VP & Group President of Medical Devices',
   'yearBorn': 1970,
   'fiscalYear': 2022,
   'totalPay': 2258516,
   'exercisedValue': 0,
   'unexercisedValue': 5997133},
  {'maxAge': 1,
   'name': 'Ms. Sabina  Ewing',
   'age': 50,
   'title': 'Senior VP of Business & Technology Services and Chief Information Officer',
   'yearBorn': 1974,
   'fiscalYear': 2022,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Michael  Comilla',
   'title': 'Vice President of Investor Relations.',
   'fiscalYear': 2022,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Erica L. Battaglia',
   'title': 'VP and Chief Ethics & Compliance Officer',
   'fiscalYear': 2022,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Elizabeth  Cushman',
   'title': 'Executive VP, General Counsel & Secretary',
   'fiscalYear': 2022,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Mary K. Moreland',
   'age': 58,
   'title': 'Executive Vice President of Human Resources',
   'yearBorn': 1966,
   'fiscalYear': 2022,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Melissa  Brotz',
   'title': 'Senior Vice President of Global Marketing & External Affairs',
   'fiscalYear': 2022,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 9,
 'boardRisk': 6,
 'compensationRisk': 9,
 'shareHolderRightsRisk': 2,
 'overallRisk': 7,
 'governanceEpochDate': 1756684800,
 'compensationAsOfEpochDate': 1672444800,
 'irWebsite': 'http://www.abbottinvestor.com/phoenix.zhtml?c=94004&p=irol-irhome',
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 132.81,
 'open': 132.515,
 'dayLow': 132.445,
 'dayHigh': 134.325,
 'regularMarketPreviousClose': 132.81,
 'regularMarketOpen': 132.515,
 'regularMarketDayLow': 132.445,
 'regularMarketDayHigh': 134.325,
 'dividendRate': 2.36,
 'dividendYield': 1.78,
 'exDividendDate': 1752537600,
 'payoutRatio': 0.2861,
 'fiveYearAvgDividendYield': 1.69,
 'beta': 0.688,
 'trailingPE': 16.659147,
 'forwardPE': 25.763567,
 'volume': 3241790,
 'regularMarketVolume': 3241790,
 'averageVolume': 6339172,
 'averageVolume10days': 4772350,
 'averageDailyVolume10Day': 4772350,
 'bid': 132.35,
 'ask': 133.26,
 'bidSize': 1,
 'askSize': 3,
 'marketCap': 231376764928,
 'fiftyTwoWeekLow': 110.86,
 'fiftyTwoWeekHigh': 141.23,
 'priceToSalesTrailing12Months': 5.36725,
 'fiftyDayAverage': 130.727,
 'twoHundredDayAverage': 127.60495,
 'trailingAnnualDividendRate': 2.32,
 'trailingAnnualDividendYield': 0.017468564,
 'currency': 'USD',
 'tradeable': False,
 'enterpriseValue': 237828620288,
 'profitMargins': 0.32426998,
 'floatShares': 1730225115,
 'sharesOutstanding': 1740460032,
 'sharesShort': 17110418,
 'sharesShortPriorMonth': 19057306,
 'sharesShortPreviousMonthDate': 1752537600,
 'dateShortInterest': 1755216000,
 'sharesPercentSharesOut': 0.0098,
 'heldPercentInsiders': 0.00543,
 'heldPercentInstitutions': 0.80875,
 'shortRatio': 2.18,
 'shortPercentOfFloat': 0.0099,
 'impliedSharesOutstanding': 1740460032,
 'bookValue': 29.053,
 'priceToBook': 4.5757756,
 'lastFiscalYearEnd': 1735603200,
 'nextFiscalYearEnd': 1767139200,
 'mostRecentQuarter': 1751241600,
 'earningsQuarterlyGrowth': 0.366,
 'netIncomeToCommon': 13927999488,
 'trailingEps': 7.98,
 'forwardEps': 5.16,
 'lastSplitFactor': '10000:4798',
 'lastSplitDate': 1357084800,
 'enterpriseToRevenue': 5.517,
 'enterpriseToEbitda': 20.766,
 '52WeekChange': 0.14180195,
 'SandP52WeekChange': 0.18469036,
 'lastDividendValue': 0.59,
 'lastDividendDate': 1752537600,
 'quoteType': 'EQUITY',
 'currentPrice': 132.94,
 'targetHighPrice': 159.0,
 'targetLowPrice': 122.0,
 'targetMeanPrice': 142.4848,
 'targetMedianPrice': 143.12,
 'recommendationMean': 1.82143,
 'recommendationKey': 'buy',
 'numberOfAnalystOpinions': 25,
 'totalCash': 7281999872,
 'totalCashPerShare': 4.184,
 'ebitda': 11452999680,
 'totalDebt': 13470000128,
 'quickRatio': 1.135,
 'currentRatio': 1.821,
 'totalRevenue': 43108999168,
 'debtToEquity': 26.501,
 'revenuePerShare': 24.777,
 'returnOnAssets': 0.06617,
 'returnOnEquity': 0.30931,
 'grossProfits': 24277999616,
 'freeCashflow': 5919750144,
 'operatingCashflow': 9036999680,
 'earningsGrowth': 0.365,
 'revenueGrowth': 0.074,
 'grossMargins': 0.56318,
 'ebitdaMargins': 0.26568002,
 'operatingMargins': 0.19726999,
 'financialCurrency': 'USD',
 'symbol': 'ABT',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Delayed Quote',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'exchange': 'NYQ',
 'messageBoardId': 'finmb_247483',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'gmtOffSetMilliseconds': -14400000,
 'market': 'us_market',
 'esgPopulated': False,
 'regularMarketChangePercent': 0.0978879,
 'regularMarketPrice': 132.94,
 'corporateActions': [],
 'postMarketTime': 1757116032,
 'regularMarketTime': 1757102410,
 'shortName': 'Abbott Laboratories',
 'longName': 'Abbott Laboratories',
 'earningsTimestampEnd': 1752755400,
 'earningsCallTimestampStart': 1752757200,
 'earningsCallTimestampEnd': 1752757200,
 'isEarningsDateEstimate': False,
 'epsTrailingTwelveMonths': 7.98,
 'epsForward': 5.16,
 'epsCurrentYear': 5.14258,
 'priceEpsCurrentYear': 25.850838,
 'fiftyDayAverageChange': 2.2129974,
 'fiftyDayAverageChangePercent': 0.016928388,
 'twoHundredDayAverageChange': 5.3350525,
 'twoHundredDayAverageChangePercent': 0.041809134,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'averageAnalystRating': '1.8 - Buy',
 'cryptoTradeable': False,
 'marketState': 'CLOSED',
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 322151400000,
 'postMarketChangePercent': 0.03008371,
 'postMarketPrice': 132.98,
 'postMarketChange': 0.039993286,
 'regularMarketChange': 0.130005,
 'regularMarketDayRange': '132.445 - 134.325',
 'fullExchangeName': 'NYSE',
 'averageDailyVolume3Month': 6339172,
 'fiftyTwoWeekLowChange': 22.080002,
 'fiftyTwoWeekLowChangePercent': 0.19917014,
 'fiftyTwoWeekRange': '110.86 - 141.23',
 'fiftyTwoWeekHighChange': -8.289993,
 'fiftyTwoWeekHighChangePercent': -0.05869853,
 'fiftyTwoWeekChangePercent': 14.180195,
 'dividendDate': 1755216000,
 'earningsTimestamp': 1752755400,
 'earningsTimestampStart': 1752755400,
 'trailingPegRatio': None}

In [11]:
print(type(df1.info))  # diccionario

<class 'dict'>

In [12]:
print("El beta de la compañia es",df1.info["beta"])  # diccionario la clave es beta

El beta de la compañia es 0.688

In [13]:
df1.info.keys()  # todos los KEYS que puedo consultar de la compañia

dict_keys(['address1', 'address2', 'city', 'state', 'zip', 'country', 'phone', 'website', 'industry', 'industryKey', 'industryDisp', 'sector', 'sectorKey', 'sectorDisp', 'longBusinessSummary', 'fullTimeEmployees', 'companyOfficers', 'auditRisk', 'boardRisk', 'compensationRisk', 'shareHolderRightsRisk', 'overallRisk', 'governanceEpochDate', 'compensationAsOfEpochDate', 'irWebsite', 'executiveTeam', 'maxAge', 'priceHint', 'previousClose', 'open', 'dayLow', 'dayHigh', 'regularMarketPreviousClose', 'regularMarketOpen', 'regularMarketDayLow', 'regularMarketDayHigh', 'dividendRate', 'dividendYield', 'exDividendDate', 'payoutRatio', 'fiveYearAvgDividendYield', 'beta', 'trailingPE', 'forwardPE', 'volume', 'regularMarketVolume', 'averageVolume', 'averageVolume10days', 'averageDailyVolume10Day', 'bid', 'ask', 'bidSize', 'askSize', 'marketCap', 'fiftyTwoWeekLow', 'fiftyTwoWeekHigh', 'priceToSalesTrailing12Months', 'fiftyDayAverage', 'twoHundredDayAverage', 'trailingAnnualDividendRate', 'trailingAnnualDividendYield', 'currency', 'tradeable', 'enterpriseValue', 'profitMargins', 'floatShares', 'sharesOutstanding', 'sharesShort', 'sharesShortPriorMonth', 'sharesShortPreviousMonthDate', 'dateShortInterest', 'sharesPercentSharesOut', 'heldPercentInsiders', 'heldPercentInstitutions', 'shortRatio', 'shortPercentOfFloat', 'impliedSharesOutstanding', 'bookValue', 'priceToBook', 'lastFiscalYearEnd', 'nextFiscalYearEnd', 'mostRecentQuarter', 'earningsQuarterlyGrowth', 'netIncomeToCommon', 'trailingEps', 'forwardEps', 'lastSplitFactor', 'lastSplitDate', 'enterpriseToRevenue', 'enterpriseToEbitda', '52WeekChange', 'SandP52WeekChange', 'lastDividendValue', 'lastDividendDate', 'quoteType', 'currentPrice', 'targetHighPrice', 'targetLowPrice', 'targetMeanPrice', 'targetMedianPrice', 'recommendationMean', 'recommendationKey', 'numberOfAnalystOpinions', 'totalCash', 'totalCashPerShare', 'ebitda', 'totalDebt', 'quickRatio', 'currentRatio', 'totalRevenue', 'debtToEquity', 'revenuePerShare', 'returnOnAssets', 'returnOnEquity', 'grossProfits', 'freeCashflow', 'operatingCashflow', 'earningsGrowth', 'revenueGrowth', 'grossMargins', 'ebitdaMargins', 'operatingMargins', 'financialCurrency', 'symbol', 'language', 'region', 'typeDisp', 'quoteSourceName', 'triggerable', 'customPriceAlertConfidence', 'exchange', 'messageBoardId', 'exchangeTimezoneName', 'exchangeTimezoneShortName', 'gmtOffSetMilliseconds', 'market', 'esgPopulated', 'regularMarketChangePercent', 'regularMarketPrice', 'corporateActions', 'postMarketTime', 'regularMarketTime', 'shortName', 'longName', 'earningsTimestampEnd', 'earningsCallTimestampStart', 'earningsCallTimestampEnd', 'isEarningsDateEstimate', 'epsTrailingTwelveMonths', 'epsForward', 'epsCurrentYear', 'priceEpsCurrentYear', 'fiftyDayAverageChange', 'fiftyDayAverageChangePercent', 'twoHundredDayAverageChange', 'twoHundredDayAverageChangePercent', 'sourceInterval', 'exchangeDataDelayedBy', 'averageAnalystRating', 'cryptoTradeable', 'marketState', 'hasPrePostMarketData', 'firstTradeDateMilliseconds', 'postMarketChangePercent', 'postMarketPrice', 'postMarketChange', 'regularMarketChange', 'regularMarketDayRange', 'fullExchangeName', 'averageDailyVolume3Month', 'fiftyTwoWeekLowChange', 'fiftyTwoWeekLowChangePercent', 'fiftyTwoWeekRange', 'fiftyTwoWeekHighChange', 'fiftyTwoWeekHighChangePercent', 'fiftyTwoWeekChangePercent', 'dividendDate', 'earningsTimestamp', 'earningsTimestampStart', 'trailingPegRatio'])

In [14]:
df1.balance_sheet  #muestra el estado de situacion

,2024-12-31,2023-12-31,2022-12-31,2021-12-31,2020-12-31
Treasury Shares Number,2.597746e+08,2.538075e+08,2.487243e+08,2.211912e+08,NaN
Ordinary Shares Number,1.731698e+09,1.734076e+09,1.737795e+09,1.764082e+09,NaN
Share Issued,1.991473e+09,1.987884e+09,1.986519e+09,1.985273e+09,NaN
Net Debt,6.509000e+09,7.783000e+09,6.891000e+09,8.251000e+09,NaN
Total Debt,1.502100e+10,1.562800e+10,1.771600e+10,1.900600e+10,NaN
...,...,...,...,...,...
Allowance For Doubtful Accounts Receivable,-4.390000e+08,-4.440000e+08,-5.000000e+08,-5.190000e+08,NaN
Gross Accounts Receivable,7.364000e+09,7.009000e+09,6.718000e+09,7.006000e+09,NaN
Cash Cash Equivalents And Short Term Investments,7.967000e+09,7.279000e+09,1.017000e+10,1.024900e+10,NaN
Other Short Term Investments,3.510000e+08,3.830000e+08,2.880000e+08,4.500000e+08,NaN
Cash And Cash Equivalents,7.616000e+09,6.896000e+09,9.882000e+09,9.799000e+09,NaN

In [15]:
df1.income_stmt  #muestra el estado de resultados

,2024-12-31,2023-12-31,2022-12-31,2021-12-31,2020-12-31
Tax Effect Of Unusual Items,5.670000e+06,-5.781000e+06,-3.306044e+05,-1.390000e+05,NaN
Tax Rate For Calcs,2.100000e-01,1.410000e-01,1.653020e-01,1.390000e-01,NaN
Normalized EBITDA,1.076300e+10,1.058500e+10,1.213300e+10,1.228300e+10,NaN
Total Unusual Items,2.700000e+07,-4.100000e+07,-2.000000e+06,-1.000000e+06,NaN
Total Unusual Items Excluding Goodwill,2.700000e+07,-4.100000e+07,-2.000000e+06,-1.000000e+06,NaN
Net Income From Continuing Operation Net Minority Interest,1.340200e+10,5.723000e+09,6.933000e+09,7.071000e+09,NaN
Reconciled Depreciation,3.218000e+09,3.243000e+09,3.267000e+09,3.538000e+09,NaN
Reconciled Cost Of Revenue,1.736600e+10,1.669800e+10,1.788800e+10,1.704600e+10,NaN
EBITDA,1.079000e+10,1.054400e+10,1.213100e+10,1.228200e+10,NaN
EBIT,7.572000e+09,7.301000e+09,8.864000e+09,8.744000e+09,NaN
Net Interest Income,-2.150000e+08,-2.520000e+08,-3.750000e+08,-4.900000e+08,NaN
Interest Expense,5.590000e+08,6.370000e+08,5.580000e+08,5.330000e+08,NaN
Interest Income,3.440000e+08,3.850000e+08,1.830000e+08,4.300000e+07,NaN
Normalized Income,1.338067e+10,5.758219e+09,6.934669e+09,7.071861e+09,NaN
Net Income From Continuing And Discontinued Operation,1.340200e+10,5.723000e+09,6.933000e+09,7.071000e+09,NaN
Total Expenses,3.512500e+10,3.363100e+10,3.529100e+10,3.465000e+10,NaN
Total Operating Income As Reported,6.825000e+09,6.478000e+09,8.362000e+09,8.425000e+09,NaN
Diluted Average Shares,1.748000e+09,1.749000e+09,1.764000e+09,1.789000e+09,NaN
Basic Average Shares,1.731698e+09,1.734076e+09,1.737795e+09,1.764082e+09,NaN
Diluted EPS,7.640000e+00,3.260000e+00,3.910000e+00,3.940000e+00,NaN
Basic EPS,7.739225e+00,3.300316e+00,3.989538e+00,4.008317e+00,NaN
Diluted NI Availto Com Stockholders,1.340200e+10,5.723000e+09,6.933000e+09,7.071000e+09,NaN
Net Income Common Stockholders,1.340200e+10,5.723000e+09,6.933000e+09,7.071000e+09,NaN
Net Income,1.340200e+10,5.723000e+09,6.933000e+09,7.071000e+09,NaN
Net Income Including Noncontrolling Interests,1.340200e+10,5.723000e+09,6.933000e+09,7.071000e+09,NaN
Net Income Discontinuous Operations,NaN,NaN,0.000000e+00,0.000000e+00,24000000.0
Net Income Continuous Operations,1.340200e+10,5.723000e+09,6.933000e+09,7.071000e+09,NaN
Tax Provision,-6.389000e+09,9.410000e+08,1.373000e+09,1.140000e+09,NaN
Pretax Income,7.013000e+09,6.664000e+09,8.306000e+09,8.211000e+09,NaN
Other Income Expense,4.030000e+08,4.380000e+08,3.190000e+08,2.760000e+08,NaN
Other Non Operating Income Expenses,3.760000e+08,4.790000e+08,3.210000e+08,2.770000e+08,NaN
Special Income Charges,NaN,NaN,NaN,0.000000e+00,0.0
Gain On Sale Of Security,2.700000e+07,-4.100000e+07,-2.000000e+06,-1.000000e+06,NaN
Net Non Operating Interest Income Expense,-2.150000e+08,-2.520000e+08,-3.750000e+08,-4.900000e+08,NaN
Interest Expense Non Operating,5.590000e+08,6.370000e+08,5.580000e+08,5.330000e+08,NaN
Interest Income Non Operating,3.440000e+08,3.850000e+08,1.830000e+08,4.300000e+07,NaN
Operating Income,6.825000e+09,6.478000e+09,8.362000e+09,8.425000e+09,NaN
Operating Expense,1.641900e+10,1.565600e+10,1.614900e+10,1.611300e+10,NaN
Depreciation Amortization Depletion Income Statement,1.878000e+09,1.966000e+09,2.013000e+09,2.047000e+09,NaN
Depreciation And Amortization In Income Statement,1.878000e+09,1.966000e+09,2.013000e+09,2.047000e+09,NaN
Amortization,1.878000e+09,1.966000e+09,2.013000e+09,2.047000e+09,NaN
Amortization Of Intangibles Income Statement,1.878000e+09,1.966000e+09,2.013000e+09,2.047000e+09,NaN
Research And Development,2.844000e+09,2.741000e+09,2.888000e+09,2.742000e+09,NaN
Selling General And Administration,1.169700e+10,1.094900e+10,1.124800e+10,1.132400e+10,NaN
Gross Profit,2.324400e+10,2.213400e+10,2.451100e+10,2.453800e+10,NaN
Cost Of Revenue,1.870600e+10,1.797500e+10,1.914200e+10,1.853700e+10,NaN
Total Revenue,4.195000e+10,4.010900e+10,4.365300e+10,4.307500e+10,NaN
Operating Revenue,4.195000e+10,4.010900e+10,4.365300e+10,4.307500e+10,NaN

In [16]:
df1.dividends.loc["2020-01-01":"2025-12-31"] #dividendos historicos desde el 2020

Date
2020-01-14 00:00:00-05:00    0.36
2020-04-14 00:00:00-04:00    0.36
2020-07-14 00:00:00-04:00    0.36
2020-10-14 00:00:00-04:00    0.36
2021-01-14 00:00:00-05:00    0.45
2021-04-14 00:00:00-04:00    0.45
2021-07-14 00:00:00-04:00    0.45
2021-10-14 00:00:00-04:00    0.45
2022-01-13 00:00:00-05:00    0.47
2022-04-13 00:00:00-04:00    0.47
2022-07-14 00:00:00-04:00    0.47
2022-10-13 00:00:00-04:00    0.47
2023-01-12 00:00:00-05:00    0.51
2023-04-13 00:00:00-04:00    0.51
2023-07-13 00:00:00-04:00    0.51
2023-10-12 00:00:00-04:00    0.51
2024-01-11 00:00:00-05:00    0.55
2024-04-12 00:00:00-04:00    0.55
2024-07-15 00:00:00-04:00    0.55
2024-10-15 00:00:00-04:00    0.55
2025-01-15 00:00:00-05:00    0.59
2025-04-15 00:00:00-04:00    0.59
2025-07-15 00:00:00-04:00    0.59
Name: Dividends, dtype: float64

In [17]:
div_anual=df1.dividends.resample("YE").sum()  # Suma de dividendos anuales
div_anual

Date
1983-12-31 00:00:00-05:00    0.026934
1984-12-31 00:00:00-05:00    0.032265
1985-12-31 00:00:00-05:00    0.037877
1986-12-31 00:00:00-05:00    0.045172
1987-12-31 00:00:00-05:00    0.039840
1988-12-31 00:00:00-05:00    0.064530
1989-12-31 00:00:00-05:00    0.075751
1990-12-31 00:00:00-05:00    0.090340
1991-12-31 00:00:00-05:00    0.107735
1992-12-31 00:00:00-05:00    0.129060
1993-12-31 00:00:00-05:00    0.148139
1994-12-31 00:00:00-05:00    0.166095
1995-12-31 00:00:00-05:00    0.184051
1996-12-31 00:00:00-05:00    0.208739
1997-12-31 00:00:00-05:00    0.296276
1998-12-31 00:00:00-05:00    0.262607
1999-12-31 00:00:00-05:00    0.296274
2000-12-31 00:00:00-05:00    0.332186
2001-12-31 00:00:00-05:00    0.368098
2002-12-31 00:00:00-05:00    0.410745
2003-12-31 00:00:00-05:00    0.435435
2004-12-31 00:00:00-05:00    1.841701
2005-12-31 00:00:00-05:00    0.520583
2006-12-31 00:00:00-05:00    0.556568
2007-12-31 00:00:00-05:00    0.609346
2008-12-31 00:00:00-05:00    0.674119
2009-12-31 00:00:00-05:00    0.748488
2010-12-31 00:00:00-05:00    0.825256
2011-12-31 00:00:00-05:00    0.902024
2012-12-31 00:00:00-05:00    0.964398
2013-12-31 00:00:00-05:00    0.560000
2014-12-31 00:00:00-05:00    0.880000
2015-12-31 00:00:00-05:00    0.960000
2016-12-31 00:00:00-05:00    1.040000
2017-12-31 00:00:00-05:00    1.060000
2018-12-31 00:00:00-05:00    1.120000
2019-12-31 00:00:00-05:00    1.280000
2020-12-31 00:00:00-05:00    1.440000
2021-12-31 00:00:00-05:00    1.800000
2022-12-31 00:00:00-05:00    1.880000
2023-12-31 00:00:00-05:00    2.040000
2024-12-31 00:00:00-05:00    2.200000
2025-12-31 00:00:00-05:00    1.770000
Freq: YE-DEC, Name: Dividends, dtype: float64

In [18]:
ratios = {"Ticker":[],"Nombre":[],"Mkt_cap":[]} #Crea un diccionario con tres claves ("Ticker", "Nombre", "Mkt_cap") y listas vacías como valores.
ratios                                          # Suele usarse para acumular datos por columnas y luego convertirlo a un DataFrame

{'Ticker': [], 'Nombre': [], 'Mkt_cap': []}

In [19]:
for i in tickers_health_ss:  # Itera símbolo por símbolo 
    df=yf.Ticker(i)          # Crea el objeto Ticker de yfinance para ese símbolo    
    ratios["Ticker"].append(i)  # Guarda el símbolo en la columna 'Ticker'
    ratios["Nombre"].append(df.info["longName"])  # Lee el nombre largo y lo agrega
    ratios["Mkt_cap"].append(df.info["marketCap"]) # Lee la capitalización y la agrega

In [20]:
ratios

{'Ticker': ['ABT',
  'BAX',
  'BDX',
  'BSX',
  'DXCM',
  'EW',
  'GEHC',
  'HOLX',
  'IDXX',
  'PODD',
  'ISRG',
  'MDT',
  'RMD',
  'RVTY',
  'STE',
  'SYK',
  'ZBH'],
 'Nombre': ['Abbott Laboratories',
  'Baxter International Inc.',
  'Becton, Dickinson and Company',
  'Boston Scientific Corporation',
  'DexCom, Inc.',
  'Edwards Lifesciences Corporation',
  'GE HealthCare Technologies Inc.',
  'Hologic, Inc.',
  'IDEXX Laboratories, Inc.',
  'Insulet Corporation',
  'Intuitive Surgical, Inc.',
  'Medtronic plc',
  'ResMed Inc.',
  'Revvity, Inc.',
  'STERIS plc',
  'Stryker Corporation',
  'Zimmer Biomet Holdings, Inc.'],
 'Mkt_cap': [231376764928,
  12542624768,
  55144169472,
  158873239552,
  31572400128,
  47519879168,
  34575441920,
  14848693248,
  51442225152,
  24526856192,
  167358562304,
  119161905152,
  40564277248,
  10056564736,
  24159744000,
  149982855168,
  20944691200]}

In [21]:
df_ratios = pd.DataFrame(ratios).sort_values(by="Mkt_cap",ascending=False) #Crea un DataFrame a partir del diccionario ratios, Ordena las filas por la columna "Mkt_cap" de mayor a menor
df_ratios

   Ticker                            Nombre       Mkt_cap
0     ABT               Abbott Laboratories  231376764928
10   ISRG          Intuitive Surgical, Inc.  167358562304
3     BSX     Boston Scientific Corporation  158873239552
15    SYK               Stryker Corporation  149982855168
11    MDT                     Medtronic plc  119161905152
2     BDX     Becton, Dickinson and Company   55144169472
8    IDXX          IDEXX Laboratories, Inc.   51442225152
5      EW  Edwards Lifesciences Corporation   47519879168
12    RMD                       ResMed Inc.   40564277248
6    GEHC   GE HealthCare Technologies Inc.   34575441920
4    DXCM                      DexCom, Inc.   31572400128
9    PODD               Insulet Corporation   24526856192
14    STE                        STERIS plc   24159744000
16    ZBH      Zimmer Biomet Holdings, Inc.   20944691200
7    HOLX                     Hologic, Inc.   14848693248
1     BAX         Baxter International Inc.   12542624768
13   RVTY                     Revvity, Inc.   10056564736

# Construccion del Altman Z Score

#### Cinco ratios clave y pesos del modelo Z-score de Altman: • X1: Working Capital/Total Assets: 1.2 • X2: Retained Earnings/Total Assets: 1.4 • X3: EBIT/Total Assets: 3.3 • X4: Market Cap/Long-Term Liabilities: 0.6 • X5: Sales/Total Assets: 1

In [22]:
# Estado de situacion
yf.Ticker("ABT").balance_sheet

,2024-12-31,2023-12-31,2022-12-31,2021-12-31,2020-12-31
Treasury Shares Number,2.597746e+08,2.538075e+08,2.487243e+08,2.211912e+08,NaN
Ordinary Shares Number,1.731698e+09,1.734076e+09,1.737795e+09,1.764082e+09,NaN
Share Issued,1.991473e+09,1.987884e+09,1.986519e+09,1.985273e+09,NaN
Net Debt,6.509000e+09,7.783000e+09,6.891000e+09,8.251000e+09,NaN
Total Debt,1.502100e+10,1.562800e+10,1.771600e+10,1.900600e+10,NaN
...,...,...,...,...,...
Allowance For Doubtful Accounts Receivable,-4.390000e+08,-4.440000e+08,-5.000000e+08,-5.190000e+08,NaN
Gross Accounts Receivable,7.364000e+09,7.009000e+09,6.718000e+09,7.006000e+09,NaN
Cash Cash Equivalents And Short Term Investments,7.967000e+09,7.279000e+09,1.017000e+10,1.024900e+10,NaN
Other Short Term Investments,3.510000e+08,3.830000e+08,2.880000e+08,4.500000e+08,NaN
Cash And Cash Equivalents,7.616000e+09,6.896000e+09,9.882000e+09,9.799000e+09,NaN

In [23]:
# Estado de Resultado
yf.Ticker("ABT").income_stmt

,2024-12-31,2023-12-31,2022-12-31,2021-12-31,2020-12-31
Tax Effect Of Unusual Items,5.670000e+06,-5.781000e+06,-3.306044e+05,-1.390000e+05,NaN
Tax Rate For Calcs,2.100000e-01,1.410000e-01,1.653020e-01,1.390000e-01,NaN
Normalized EBITDA,1.076300e+10,1.058500e+10,1.213300e+10,1.228300e+10,NaN
Total Unusual Items,2.700000e+07,-4.100000e+07,-2.000000e+06,-1.000000e+06,NaN
Total Unusual Items Excluding Goodwill,2.700000e+07,-4.100000e+07,-2.000000e+06,-1.000000e+06,NaN
Net Income From Continuing Operation Net Minority Interest,1.340200e+10,5.723000e+09,6.933000e+09,7.071000e+09,NaN
Reconciled Depreciation,3.218000e+09,3.243000e+09,3.267000e+09,3.538000e+09,NaN
Reconciled Cost Of Revenue,1.736600e+10,1.669800e+10,1.788800e+10,1.704600e+10,NaN
EBITDA,1.079000e+10,1.054400e+10,1.213100e+10,1.228200e+10,NaN
EBIT,7.572000e+09,7.301000e+09,8.864000e+09,8.744000e+09,NaN
Net Interest Income,-2.150000e+08,-2.520000e+08,-3.750000e+08,-4.900000e+08,NaN
Interest Expense,5.590000e+08,6.370000e+08,5.580000e+08,5.330000e+08,NaN
Interest Income,3.440000e+08,3.850000e+08,1.830000e+08,4.300000e+07,NaN
Normalized Income,1.338067e+10,5.758219e+09,6.934669e+09,7.071861e+09,NaN
Net Income From Continuing And Discontinued Operation,1.340200e+10,5.723000e+09,6.933000e+09,7.071000e+09,NaN
Total Expenses,3.512500e+10,3.363100e+10,3.529100e+10,3.465000e+10,NaN
Total Operating Income As Reported,6.825000e+09,6.478000e+09,8.362000e+09,8.425000e+09,NaN
Diluted Average Shares,1.748000e+09,1.749000e+09,1.764000e+09,1.789000e+09,NaN
Basic Average Shares,1.731698e+09,1.734076e+09,1.737795e+09,1.764082e+09,NaN
Diluted EPS,7.640000e+00,3.260000e+00,3.910000e+00,3.940000e+00,NaN
Basic EPS,7.739225e+00,3.300316e+00,3.989538e+00,4.008317e+00,NaN
Diluted NI Availto Com Stockholders,1.340200e+10,5.723000e+09,6.933000e+09,7.071000e+09,NaN
Net Income Common Stockholders,1.340200e+10,5.723000e+09,6.933000e+09,7.071000e+09,NaN
Net Income,1.340200e+10,5.723000e+09,6.933000e+09,7.071000e+09,NaN
Net Income Including Noncontrolling Interests,1.340200e+10,5.723000e+09,6.933000e+09,7.071000e+09,NaN
Net Income Discontinuous Operations,NaN,NaN,0.000000e+00,0.000000e+00,24000000.0
Net Income Continuous Operations,1.340200e+10,5.723000e+09,6.933000e+09,7.071000e+09,NaN
Tax Provision,-6.389000e+09,9.410000e+08,1.373000e+09,1.140000e+09,NaN
Pretax Income,7.013000e+09,6.664000e+09,8.306000e+09,8.211000e+09,NaN
Other Income Expense,4.030000e+08,4.380000e+08,3.190000e+08,2.760000e+08,NaN
Other Non Operating Income Expenses,3.760000e+08,4.790000e+08,3.210000e+08,2.770000e+08,NaN
Special Income Charges,NaN,NaN,NaN,0.000000e+00,0.0
Gain On Sale Of Security,2.700000e+07,-4.100000e+07,-2.000000e+06,-1.000000e+06,NaN
Net Non Operating Interest Income Expense,-2.150000e+08,-2.520000e+08,-3.750000e+08,-4.900000e+08,NaN
Interest Expense Non Operating,5.590000e+08,6.370000e+08,5.580000e+08,5.330000e+08,NaN
Interest Income Non Operating,3.440000e+08,3.850000e+08,1.830000e+08,4.300000e+07,NaN
Operating Income,6.825000e+09,6.478000e+09,8.362000e+09,8.425000e+09,NaN
Operating Expense,1.641900e+10,1.565600e+10,1.614900e+10,1.611300e+10,NaN
Depreciation Amortization Depletion Income Statement,1.878000e+09,1.966000e+09,2.013000e+09,2.047000e+09,NaN
Depreciation And Amortization In Income Statement,1.878000e+09,1.966000e+09,2.013000e+09,2.047000e+09,NaN
Amortization,1.878000e+09,1.966000e+09,2.013000e+09,2.047000e+09,NaN
Amortization Of Intangibles Income Statement,1.878000e+09,1.966000e+09,2.013000e+09,2.047000e+09,NaN
Research And Development,2.844000e+09,2.741000e+09,2.888000e+09,2.742000e+09,NaN
Selling General And Administration,1.169700e+10,1.094900e+10,1.124800e+10,1.132400e+10,NaN
Gross Profit,2.324400e+10,2.213400e+10,2.451100e+10,2.453800e+10,NaN
Cost Of Revenue,1.870600e+10,1.797500e+10,1.914200e+10,1.853700e+10,NaN
Total Revenue,4.195000e+10,4.010900e+10,4.365300e+10,4.307500e+10,NaN
Operating Revenue,4.195000e+10,4.010900e+10,4.365300e+10,4.307500e+10,NaN

In [24]:
yf.Ticker("BDX").balance_sheet  # la fecha es distinta

,2024-09-30,2023-09-30,2022-09-30,2021-09-30,2020-09-30
Treasury Shares Number,8.149308e+07,8.020261e+07,8.128319e+07,8.016395e+07,NaN
Ordinary Shares Number,2.891013e+08,2.903918e+08,2.833567e+08,2.844760e+08,NaN
Share Issued,3.705944e+08,3.705944e+08,3.646399e+08,3.646399e+08,NaN
Net Debt,1.839300e+10,1.446300e+10,1.505900e+10,1.532700e+10,NaN
Total Debt,2.011000e+10,1.587900e+10,1.606500e+10,1.761000e+10,NaN
...,...,...,...,...,...
Allowance For Doubtful Accounts Receivable,-7.900000e+07,-8.100000e+07,NaN,NaN,NaN
Gross Accounts Receivable,3.112000e+09,2.615000e+09,NaN,NaN,NaN
Cash Cash Equivalents And Short Term Investments,2.162000e+09,1.424000e+09,1.014000e+09,2.295000e+09,NaN
Other Short Term Investments,4.450000e+08,8.000000e+06,8.000000e+06,1.200000e+07,NaN
Cash And Cash Equivalents,1.717000e+09,1.416000e+09,1.006000e+09,2.283000e+09,NaN

##### X1: Working capital/ total assets : 1.2

In [25]:
# Primera opcion
print(yf.Ticker("ABT").balance_sheet.loc["Current Assets","2024-12-31"])
print(yf.Ticker("ABT").balance_sheet.loc["Current Liabilities","2024-12-31"])
print("Working Capital: USD",yf.Ticker("ABT").balance_sheet.loc["Current Assets","2024-12-31"]- yf.Ticker("ABT").balance_sheet.loc["Current Liabilities","2024-12-31"])
print("Working Capital: USD",yf.Ticker("ABT").balance_sheet.loc["Working Capital", "2024-12-31"])

23656000000.0
14157000000.0
Working Capital: USD 9499000000.0
Working Capital: USD 9499000000.0

In [26]:
ratios = {"Ticker":[],"Nombre":[],"Mkt_cap":[],"WK":[],"Total_Assets":[],"Retained Earnings":[],"EBIT":[],"LT_Debt":[],"Revenue":[]}

In [27]:
for i in tickers_health_ss:    # Recorre cada ticker
    df=yf.Ticker(i)             # Crea el objeto Ticker de yfinance para ese símbolo
    ratios["Ticker"].append(i)    # Agrega el ticker a la columna 'Ticker'
    ratios["Nombre"].append(df.info["longName"])    # Agrega el nombre largo desde el dict df.info
    ratios["Mkt_cap"].append(df.info["marketCap"])    # Agrega la capitalización bursátil (marketCap) desde df.info
    ratios["WK"].append(df.balance_sheet.loc["Working Capital",df.balance_sheet.columns[0]])   # Agrega Working Capital desde el balance,  # Usa la 1ª columna (suele ser el período más reciente)
    ratios["Total_Assets"].append(df.balance_sheet.loc["Total Assets",df.balance_sheet.columns[0]])  # Total de activos del último período
    ratios["Retained Earnings"].append(df.balance_sheet.loc["Retained Earnings",df.balance_sheet.columns[0]])    # Utilidades retenidas del último período
    ratios["EBIT"].append(df.income_stmt.loc["EBIT",df.income_stmt.columns[0]])  # EBIT desde el estado de resultados
    ratios["LT_Debt"].append(df.balance_sheet.loc["Long Term Debt And Capital Lease Obligation",df.balance_sheet.columns[0]])   # 1ª columna (período más reciente)
    ratios["Revenue"].append(df.income_stmt.loc["Total Revenue",df.income_stmt.columns[0]])  

ratios   # Muestra el diccionario ya llenado
df_ratios=pd.DataFrame(ratios).sort_values(by="Mkt_cap", ascending=False)    # Crea DataFrame y ordena por Mkt_cap desc.  
df_ratios   # Muestra la tabla final

,Ticker,Nombre,Mkt_cap,WK,Total_Assets,Retained Earnings,EBIT,LT_Debt,Revenue
0,ABT,Abbott Laboratories,231376764928,9.499000e+09,8.141400e+10,4.726100e+10,7.572000e+09,1.352100e+10,4.195000e+10
10,ISRG,"Intuitive Surgical, Inc.",167358562304,5.365700e+09,1.874320e+10,6.803300e+09,2.348900e+09,NaN,8.352100e+09
3,BSX,Boston Scientific Corporation,158873239552,5.210000e+08,3.939500e+10,2.673000e+09,2.587000e+09,9.369000e+09,1.674700e+10
15,SYK,Stryker Corporation,149982855168,7.231000e+09,4.297100e+10,1.852800e+10,4.666000e+09,1.218800e+10,2.259500e+10
11,MDT,Medtronic plc,119161905152,1.093500e+10,9.168000e+10,3.147600e+10,6.357000e+09,2.564200e+10,3.353700e+10
2,BDX,"Becton, Dickinson and Company",55144169472,1.512000e+09,5.728600e+10,1.613900e+10,2.533000e+09,1.794000e+10,2.017800e+10
8,IDXX,"IDEXX Laboratories, Inc.",51442225152,3.319810e+08,3.293443e+09,5.332438e+09,1.141036e+09,5.476220e+08,3.897504e+09
5,EW,Edwards Lifesciences Corporation,47519879168,4.780200e+09,1.305530e+10,1.316700e+10,1.567900e+09,6.766000e+08,5.439500e+09
12,RMD,ResMed Inc.,40564277248,2.486485e+09,8.174391e+09,6.081490e+09,1.687394e+09,8.114070e+08,5.146327e+09
6,GEHC,GE HealthCare Technologies Inc.,34575441920,3.480000e+08,3.308900e+10,3.262000e+09,3.086000e+09,7.759000e+09,1.967200e+10
4,DXCM,"DexCom, Inc.",31572400128,1.369400e+09,6.484500e+09,1.597600e+09,7.280000e+08,1.360500e+09,4.033000e+09
9,PODD,Insulet Corporation,24526856192,1.362900e+09,3.087700e+09,4.030000e+07,3.429000e+08,1.296100e+09,2.071600e+09
14,STE,STERIS plc,24159744000,9.785920e+08,1.014681e+10,2.475330e+09,8.824680e+08,2.043338e+09,5.459515e+09
16,ZBH,"Zimmer Biomet Holdings, Inc.",20944691200,2.220600e+09,2.136530e+10,1.109530e+10,1.254600e+09,5.341600e+09,7.678600e+09
7,HOLX,"Hologic, Inc.",14848693248,2.786100e+09,9.156000e+09,2.845800e+09,9.872000e+08,2.593200e+09,4.030300e+09
1,BAX,Baxter International Inc.,12542624768,2.342000e+09,2.578200e+10,1.492900e+10,1.190000e+08,1.061700e+10,1.063600e+10
13,RVTY,"Revvity, Inc.",10056564736,1.696508e+09,1.239248e+10,5.845223e+09,4.124040e+08,3.301981e+09,2.755026e+09

In [28]:
df_ratios["X1"]=df_ratios["WK"]/df_ratios["Total_Assets"]  # Capital de trabajo / Activos totales
df_ratios["X2"]=df_ratios["Retained Earnings"]/df_ratios["Total_Assets"]     # Utilidades retenidas / Activos totales
df_ratios["X3"]=df_ratios["EBIT"]/df_ratios["Total_Assets"]    # EBIT / Activos totales
df_ratios["X4"]=df_ratios["Mkt_cap"]/df_ratios["LT_Debt"]       # Valor de mercado / Deuda LP
df_ratios["X5"]=df_ratios["Revenue"]/df_ratios["Total_Assets"]   # Ventas (Revenue) / Activos totales

In [29]:
df_ratios

,Ticker,Nombre,Mkt_cap,WK,Total_Assets,Retained Earnings,EBIT,LT_Debt,Revenue,X1,X2,X3,X4,X5
0,ABT,Abbott Laboratories,231376764928,9.499000e+09,8.141400e+10,4.726100e+10,7.572000e+09,1.352100e+10,4.195000e+10,0.116675,0.580502,0.093006,17.112400,0.515268
10,ISRG,"Intuitive Surgical, Inc.",167358562304,5.365700e+09,1.874320e+10,6.803300e+09,2.348900e+09,NaN,8.352100e+09,0.286274,0.362974,0.125320,NaN,0.445607
3,BSX,Boston Scientific Corporation,158873239552,5.210000e+08,3.939500e+10,2.673000e+09,2.587000e+09,9.369000e+09,1.674700e+10,0.013225,0.067851,0.065668,16.957332,0.425105
15,SYK,Stryker Corporation,149982855168,7.231000e+09,4.297100e+10,1.852800e+10,4.666000e+09,1.218800e+10,2.259500e+10,0.168276,0.431175,0.108585,12.305781,0.525820
11,MDT,Medtronic plc,119161905152,1.093500e+10,9.168000e+10,3.147600e+10,6.357000e+09,2.564200e+10,3.353700e+10,0.119274,0.343325,0.069339,4.647138,0.365805
2,BDX,"Becton, Dickinson and Company",55144169472,1.512000e+09,5.728600e+10,1.613900e+10,2.533000e+09,1.794000e+10,2.017800e+10,0.026394,0.281727,0.044217,3.073811,0.352233
8,IDXX,"IDEXX Laboratories, Inc.",51442225152,3.319810e+08,3.293443e+09,5.332438e+09,1.141036e+09,5.476220e+08,3.897504e+09,0.100801,1.619107,0.346457,93.937470,1.183413
5,EW,Edwards Lifesciences Corporation,47519879168,4.780200e+09,1.305530e+10,1.316700e+10,1.567900e+09,6.766000e+08,5.439500e+09,0.366150,1.008556,0.120097,70.233342,0.416651
12,RMD,ResMed Inc.,40564277248,2.486485e+09,8.174391e+09,6.081490e+09,1.687394e+09,8.114070e+08,5.146327e+09,0.304180,0.743969,0.206424,49.992516,0.629567
6,GEHC,GE HealthCare Technologies Inc.,34575441920,3.480000e+08,3.308900e+10,3.262000e+09,3.086000e+09,7.759000e+09,1.967200e+10,0.010517,0.098583,0.093264,4.456172,0.594518
4,DXCM,"DexCom, Inc.",31572400128,1.369400e+09,6.484500e+09,1.597600e+09,7.280000e+08,1.360500e+09,4.033000e+09,0.211181,0.246372,0.112268,23.206468,0.621945
9,PODD,Insulet Corporation,24526856192,1.362900e+09,3.087700e+09,4.030000e+07,3.429000e+08,1.296100e+09,2.071600e+09,0.441397,0.013052,0.111054,18.923583,0.670920
14,STE,STERIS plc,24159744000,9.785920e+08,1.014681e+10,2.475330e+09,8.824680e+08,2.043338e+09,5.459515e+09,0.096443,0.243952,0.086970,11.823665,0.538052
16,ZBH,"Zimmer Biomet Holdings, Inc.",20944691200,2.220600e+09,2.136530e+10,1.109530e+10,1.254600e+09,5.341600e+09,7.678600e+09,0.103935,0.519314,0.058721,3.921052,0.359396
7,HOLX,"Hologic, Inc.",14848693248,2.786100e+09,9.156000e+09,2.845800e+09,9.872000e+08,2.593200e+09,4.030300e+09,0.304292,0.310813,0.107820,5.726012,0.440181
1,BAX,Baxter International Inc.,12542624768,2.342000e+09,2.578200e+10,1.492900e+10,1.190000e+08,1.061700e+10,1.063600e+10,0.090839,0.579047,0.004616,1.181372,0.412536
13,RVTY,"Revvity, Inc.",10056564736,1.696508e+09,1.239248e+10,5.845223e+09,4.124040e+08,3.301981e+09,2.755026e+09,0.136898,0.471675,0.033279,3.045616,0.222314

### Fórmula de Altman Z-Score
Z= 1.2X1 + 1.4X2 + 3.3X3 + 0.6X4 + 1X5.

Esta herramienta clasifica a las empresas en las siguientes categorías según
su puntuación Z:
- Zona en dificultades (Z < 1.81): indica alto riesgo de quiebra. Se
recomienda precaución.
- Zona gris (1.81<Z<3): muestra una posición financiera precaria. Se
recomienda vigilancia.
- Zona Segura (Z > 3): indica estabilidad y bienestar financiero.

In [30]:
df_ratios["Z"]=1.2*df_ratios["X1"]+1.4*df_ratios["X2"]+3.3*df_ratios["X3"]+0.6*df_ratios["X4"]+1*df_ratios["X5"]
df_ratios

,Ticker,Nombre,Mkt_cap,WK,Total_Assets,Retained Earnings,EBIT,LT_Debt,Revenue,X1,X2,X3,X4,X5,Z
0,ABT,Abbott Laboratories,231376764928,9.499000e+09,8.141400e+10,4.726100e+10,7.572000e+09,1.352100e+10,4.195000e+10,0.116675,0.580502,0.093006,17.112400,0.515268,12.042341
10,ISRG,"Intuitive Surgical, Inc.",167358562304,5.365700e+09,1.874320e+10,6.803300e+09,2.348900e+09,NaN,8.352100e+09,0.286274,0.362974,0.125320,NaN,0.445607,NaN
3,BSX,Boston Scientific Corporation,158873239552,5.210000e+08,3.939500e+10,2.673000e+09,2.587000e+09,9.369000e+09,1.674700e+10,0.013225,0.067851,0.065668,16.957332,0.425105,10.927071
15,SYK,Stryker Corporation,149982855168,7.231000e+09,4.297100e+10,1.852800e+10,4.666000e+09,1.218800e+10,2.259500e+10,0.168276,0.431175,0.108585,12.305781,0.525820,9.073194
11,MDT,Medtronic plc,119161905152,1.093500e+10,9.168000e+10,3.147600e+10,6.357000e+09,2.564200e+10,3.353700e+10,0.119274,0.343325,0.069339,4.647138,0.365805,4.006689
2,BDX,"Becton, Dickinson and Company",55144169472,1.512000e+09,5.728600e+10,1.613900e+10,2.533000e+09,1.794000e+10,2.017800e+10,0.026394,0.281727,0.044217,3.073811,0.352233,2.768525
8,IDXX,"IDEXX Laboratories, Inc.",51442225152,3.319810e+08,3.293443e+09,5.332438e+09,1.141036e+09,5.476220e+08,3.897504e+09,0.100801,1.619107,0.346457,93.937470,1.183413,61.076914
5,EW,Edwards Lifesciences Corporation,47519879168,4.780200e+09,1.305530e+10,1.316700e+10,1.567900e+09,6.766000e+08,5.439500e+09,0.366150,1.008556,0.120097,70.233342,0.416651,44.804334
12,RMD,ResMed Inc.,40564277248,2.486485e+09,8.174391e+09,6.081490e+09,1.687394e+09,8.114070e+08,5.146327e+09,0.304180,0.743969,0.206424,49.992516,0.629567,32.712849
6,GEHC,GE HealthCare Technologies Inc.,34575441920,3.480000e+08,3.308900e+10,3.262000e+09,3.086000e+09,7.759000e+09,1.967200e+10,0.010517,0.098583,0.093264,4.456172,0.594518,3.726627
4,DXCM,"DexCom, Inc.",31572400128,1.369400e+09,6.484500e+09,1.597600e+09,7.280000e+08,1.360500e+09,4.033000e+09,0.211181,0.246372,0.112268,23.206468,0.621945,15.514647
9,PODD,Insulet Corporation,24526856192,1.362900e+09,3.087700e+09,4.030000e+07,3.429000e+08,1.296100e+09,2.071600e+09,0.441397,0.013052,0.111054,18.923583,0.670920,12.939495
14,STE,STERIS plc,24159744000,9.785920e+08,1.014681e+10,2.475330e+09,8.824680e+08,2.043338e+09,5.459515e+09,0.096443,0.243952,0.086970,11.823665,0.538052,8.376516
16,ZBH,"Zimmer Biomet Holdings, Inc.",20944691200,2.220600e+09,2.136530e+10,1.109530e+10,1.254600e+09,5.341600e+09,7.678600e+09,0.103935,0.519314,0.058721,3.921052,0.359396,3.757569
7,HOLX,"Hologic, Inc.",14848693248,2.786100e+09,9.156000e+09,2.845800e+09,9.872000e+08,2.593200e+09,4.030300e+09,0.304292,0.310813,0.107820,5.726012,0.440181,5.031883
1,BAX,Baxter International Inc.,12542624768,2.342000e+09,2.578200e+10,1.492900e+10,1.190000e+08,1.061700e+10,1.063600e+10,0.090839,0.579047,0.004616,1.181372,0.412536,2.056263
13,RVTY,"Revvity, Inc.",10056564736,1.696508e+09,1.239248e+10,5.845223e+09,4.124040e+08,3.301981e+09,2.755026e+09,0.136898,0.471675,0.033279,3.045616,0.222314,2.984126

In [31]:
# funcion para clasficar la empresa segun el caluclo de su ratio de Altman Z-Score
def altman_z_score_classification(z):
    if z>3.0:
        return "Saludable"
    elif z>1.81:
        return "En vigilancia"
    else:
        return "En riesgo de quiebra"

In [32]:
altman_z_score_classification(3.05)

'Saludable'

In [33]:
df_ratios["Z_Classification"]=df_ratios["Z"].apply(altman_z_score_classification)
df_ratios

,Ticker,Nombre,Mkt_cap,WK,Total_Assets,Retained Earnings,EBIT,LT_Debt,Revenue,X1,X2,X3,X4,X5,Z,Z_Classification
0,ABT,Abbott Laboratories,231376764928,9.499000e+09,8.141400e+10,4.726100e+10,7.572000e+09,1.352100e+10,4.195000e+10,0.116675,0.580502,0.093006,17.112400,0.515268,12.042341,Saludable
10,ISRG,"Intuitive Surgical, Inc.",167358562304,5.365700e+09,1.874320e+10,6.803300e+09,2.348900e+09,NaN,8.352100e+09,0.286274,0.362974,0.125320,NaN,0.445607,NaN,En riesgo de quiebra
3,BSX,Boston Scientific Corporation,158873239552,5.210000e+08,3.939500e+10,2.673000e+09,2.587000e+09,9.369000e+09,1.674700e+10,0.013225,0.067851,0.065668,16.957332,0.425105,10.927071,Saludable
15,SYK,Stryker Corporation,149982855168,7.231000e+09,4.297100e+10,1.852800e+10,4.666000e+09,1.218800e+10,2.259500e+10,0.168276,0.431175,0.108585,12.305781,0.525820,9.073194,Saludable
11,MDT,Medtronic plc,119161905152,1.093500e+10,9.168000e+10,3.147600e+10,6.357000e+09,2.564200e+10,3.353700e+10,0.119274,0.343325,0.069339,4.647138,0.365805,4.006689,Saludable
2,BDX,"Becton, Dickinson and Company",55144169472,1.512000e+09,5.728600e+10,1.613900e+10,2.533000e+09,1.794000e+10,2.017800e+10,0.026394,0.281727,0.044217,3.073811,0.352233,2.768525,En vigilancia
8,IDXX,"IDEXX Laboratories, Inc.",51442225152,3.319810e+08,3.293443e+09,5.332438e+09,1.141036e+09,5.476220e+08,3.897504e+09,0.100801,1.619107,0.346457,93.937470,1.183413,61.076914,Saludable
5,EW,Edwards Lifesciences Corporation,47519879168,4.780200e+09,1.305530e+10,1.316700e+10,1.567900e+09,6.766000e+08,5.439500e+09,0.366150,1.008556,0.120097,70.233342,0.416651,44.804334,Saludable
12,RMD,ResMed Inc.,40564277248,2.486485e+09,8.174391e+09,6.081490e+09,1.687394e+09,8.114070e+08,5.146327e+09,0.304180,0.743969,0.206424,49.992516,0.629567,32.712849,Saludable
6,GEHC,GE HealthCare Technologies Inc.,34575441920,3.480000e+08,3.308900e+10,3.262000e+09,3.086000e+09,7.759000e+09,1.967200e+10,0.010517,0.098583,0.093264,4.456172,0.594518,3.726627,Saludable
4,DXCM,"DexCom, Inc.",31572400128,1.369400e+09,6.484500e+09,1.597600e+09,7.280000e+08,1.360500e+09,4.033000e+09,0.211181,0.246372,0.112268,23.206468,0.621945,15.514647,Saludable
9,PODD,Insulet Corporation,24526856192,1.362900e+09,3.087700e+09,4.030000e+07,3.429000e+08,1.296100e+09,2.071600e+09,0.441397,0.013052,0.111054,18.923583,0.670920,12.939495,Saludable
14,STE,STERIS plc,24159744000,9.785920e+08,1.014681e+10,2.475330e+09,8.824680e+08,2.043338e+09,5.459515e+09,0.096443,0.243952,0.086970,11.823665,0.538052,8.376516,Saludable
16,ZBH,"Zimmer Biomet Holdings, Inc.",20944691200,2.220600e+09,2.136530e+10,1.109530e+10,1.254600e+09,5.341600e+09,7.678600e+09,0.103935,0.519314,0.058721,3.921052,0.359396,3.757569,Saludable
7,HOLX,"Hologic, Inc.",14848693248,2.786100e+09,9.156000e+09,2.845800e+09,9.872000e+08,2.593200e+09,4.030300e+09,0.304292,0.310813,0.107820,5.726012,0.440181,5.031883,Saludable
1,BAX,Baxter International Inc.,12542624768,2.342000e+09,2.578200e+10,1.492900e+10,1.190000e+08,1.061700e+10,1.063600e+10,0.090839,0.579047,0.004616,1.181372,0.412536,2.056263,En vigilancia
13,RVTY,"Revvity, Inc.",10056564736,1.696508e+09,1.239248e+10,5.845223e+09,4.124040e+08,3.301981e+09,2.755026e+09,0.136898,0.471675,0.033279,3.045616,0.222314,2.984126,En vigilancia